/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainTaskManagerIndexRouteImport } from './routes/_main/task-manager/index'
import { Route as MainSuppliersIndexRouteImport } from './routes/_main/suppliers/index'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings/index'
import { Route as MainRollingPlansIndexRouteImport } from './routes/_main/rolling-plans/index'
import { Route as MainReadyStripsIndexRouteImport } from './routes/_main/ready-strips/index'
import { Route as MainReadyProductsIndexRouteImport } from './routes/_main/ready-products/index'
import { Route as MainRawMaterialsIndexRouteImport } from './routes/_main/raw-materials/index'
import { Route as MainRawMaterialRequestsIndexRouteImport } from './routes/_main/raw-material-requests/index'
import { Route as MainOrdersIndexRouteImport } from './routes/_main/orders/index'
import { Route as MainManufacturesIndexRouteImport } from './routes/_main/manufactures/index'
import { Route as MainFinanceIndexRouteImport } from './routes/_main/finance/index'
import { Route as MainExtraIndexRouteImport } from './routes/_main/extra/index'
import { Route as MainDemandsIndexRouteImport } from './routes/_main/demands/index'
import { Route as MainDashboardIndexRouteImport } from './routes/_main/dashboard/index'
import { Route as MainClientsIndexRouteImport } from './routes/_main/clients/index'
import { Route as MainAdminsIndexRouteImport } from './routes/_main/admins/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as MainSettingsRawMaterialsIndexRouteImport } from './routes/_main/settings/raw-materials/index'
import { Route as MainSettingsProductsIndexRouteImport } from './routes/_main/settings/products/index'
import { Route as MainSettingsPaymentTypeIndexRouteImport } from './routes/_main/settings/payment-type/index'
import { Route as MainSettingsMachineIndexRouteImport } from './routes/_main/settings/machine/index'
import { Route as MainSettingsFinanceCategoryIndexRouteImport } from './routes/_main/settings/finance-category/index'
import { Route as MainSettingsCurrencyIndexRouteImport } from './routes/_main/settings/currency/index'
import { Route as MainReadyStripsManufactureIdIndexRouteImport } from './routes/_main/ready-strips/$manufactureId/index'
import { Route as MainFinanceSalaryIndexRouteImport } from './routes/_main/finance/salary/index'
import { Route as MainFinanceIncomeIndexRouteImport } from './routes/_main/finance/income/index'
import { Route as MainFinanceExpenceIndexRouteImport } from './routes/_main/finance/expence/index'
import { Route as MainFinanceDashboardIndexRouteImport } from './routes/_main/finance/dashboard/index'
import { Route as MainFinanceCashFlowIndexRouteImport } from './routes/_main/finance/cash-flow/index'
import { Route as MainSettingsProductsCategoryIdIndexRouteImport } from './routes/_main/settings/products/$categoryId/index'
import { Route as MainSettingsProductsCategoryIdSubcategoryIdIndexRouteImport } from './routes/_main/settings/products/$categoryId/$subcategoryId/index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainTaskManagerIndexRoute = MainTaskManagerIndexRouteImport.update({
  id: '/task-manager/',
  path: '/task-manager/',
  getParentRoute: () => MainRoute,
} as any)
const MainSuppliersIndexRoute = MainSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRoute,
} as any)
const MainRollingPlansIndexRoute = MainRollingPlansIndexRouteImport.update({
  id: '/rolling-plans/',
  path: '/rolling-plans/',
  getParentRoute: () => MainRoute,
} as any)
const MainReadyStripsIndexRoute = MainReadyStripsIndexRouteImport.update({
  id: '/ready-strips/',
  path: '/ready-strips/',
  getParentRoute: () => MainRoute,
} as any)
const MainReadyProductsIndexRoute = MainReadyProductsIndexRouteImport.update({
  id: '/ready-products/',
  path: '/ready-products/',
  getParentRoute: () => MainRoute,
} as any)
const MainRawMaterialsIndexRoute = MainRawMaterialsIndexRouteImport.update({
  id: '/raw-materials/',
  path: '/raw-materials/',
  getParentRoute: () => MainRoute,
} as any)
const MainRawMaterialRequestsIndexRoute =
  MainRawMaterialRequestsIndexRouteImport.update({
    id: '/raw-material-requests/',
    path: '/raw-material-requests/',
    getParentRoute: () => MainRoute,
  } as any)
const MainOrdersIndexRoute = MainOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => MainRoute,
} as any)
const MainManufacturesIndexRoute = MainManufacturesIndexRouteImport.update({
  id: '/manufactures/',
  path: '/manufactures/',
  getParentRoute: () => MainRoute,
} as any)
const MainFinanceIndexRoute = MainFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => MainRoute,
} as any)
const MainExtraIndexRoute = MainExtraIndexRouteImport.update({
  id: '/extra/',
  path: '/extra/',
  getParentRoute: () => MainRoute,
} as any)
const MainDemandsIndexRoute = MainDemandsIndexRouteImport.update({
  id: '/demands/',
  path: '/demands/',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardIndexRoute = MainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => MainRoute,
} as any)
const MainClientsIndexRoute = MainClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminsIndexRoute = MainAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => MainRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const MainSettingsRawMaterialsIndexRoute =
  MainSettingsRawMaterialsIndexRouteImport.update({
    id: '/settings/raw-materials/',
    path: '/settings/raw-materials/',
    getParentRoute: () => MainRoute,
  } as any)
const MainSettingsProductsIndexRoute =
  MainSettingsProductsIndexRouteImport.update({
    id: '/settings/products/',
    path: '/settings/products/',
    getParentRoute: () => MainRoute,
  } as any)
const MainSettingsPaymentTypeIndexRoute =
  MainSettingsPaymentTypeIndexRouteImport.update({
    id: '/settings/payment-type/',
    path: '/settings/payment-type/',
    getParentRoute: () => MainRoute,
  } as any)
const MainSettingsMachineIndexRoute =
  MainSettingsMachineIndexRouteImport.update({
    id: '/settings/machine/',
    path: '/settings/machine/',
    getParentRoute: () => MainRoute,
  } as any)
const MainSettingsFinanceCategoryIndexRoute =
  MainSettingsFinanceCategoryIndexRouteImport.update({
    id: '/settings/finance-category/',
    path: '/settings/finance-category/',
    getParentRoute: () => MainRoute,
  } as any)
const MainSettingsCurrencyIndexRoute =
  MainSettingsCurrencyIndexRouteImport.update({
    id: '/settings/currency/',
    path: '/settings/currency/',
    getParentRoute: () => MainRoute,
  } as any)
const MainReadyStripsManufactureIdIndexRoute =
  MainReadyStripsManufactureIdIndexRouteImport.update({
    id: '/ready-strips/$manufactureId/',
    path: '/ready-strips/$manufactureId/',
    getParentRoute: () => MainRoute,
  } as any)
const MainFinanceSalaryIndexRoute = MainFinanceSalaryIndexRouteImport.update({
  id: '/finance/salary/',
  path: '/finance/salary/',
  getParentRoute: () => MainRoute,
} as any)
const MainFinanceIncomeIndexRoute = MainFinanceIncomeIndexRouteImport.update({
  id: '/finance/income/',
  path: '/finance/income/',
  getParentRoute: () => MainRoute,
} as any)
const MainFinanceExpenceIndexRoute = MainFinanceExpenceIndexRouteImport.update({
  id: '/finance/expence/',
  path: '/finance/expence/',
  getParentRoute: () => MainRoute,
} as any)
const MainFinanceDashboardIndexRoute =
  MainFinanceDashboardIndexRouteImport.update({
    id: '/finance/dashboard/',
    path: '/finance/dashboard/',
    getParentRoute: () => MainRoute,
  } as any)
const MainFinanceCashFlowIndexRoute =
  MainFinanceCashFlowIndexRouteImport.update({
    id: '/finance/cash-flow/',
    path: '/finance/cash-flow/',
    getParentRoute: () => MainRoute,
  } as any)
const MainSettingsProductsCategoryIdIndexRoute =
  MainSettingsProductsCategoryIdIndexRouteImport.update({
    id: '/settings/products/$categoryId/',
    path: '/settings/products/$categoryId/',
    getParentRoute: () => MainRoute,
  } as any)
const MainSettingsProductsCategoryIdSubcategoryIdIndexRoute =
  MainSettingsProductsCategoryIdSubcategoryIdIndexRouteImport.update({
    id: '/settings/products/$categoryId/$subcategoryId/',
    path: '/settings/products/$categoryId/$subcategoryId/',
    getParentRoute: () => MainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/admins': typeof MainAdminsIndexRoute
  '/clients': typeof MainClientsIndexRoute
  '/dashboard': typeof MainDashboardIndexRoute
  '/demands': typeof MainDemandsIndexRoute
  '/extra': typeof MainExtraIndexRoute
  '/finance': typeof MainFinanceIndexRoute
  '/manufactures': typeof MainManufacturesIndexRoute
  '/orders': typeof MainOrdersIndexRoute
  '/raw-material-requests': typeof MainRawMaterialRequestsIndexRoute
  '/raw-materials': typeof MainRawMaterialsIndexRoute
  '/ready-products': typeof MainReadyProductsIndexRoute
  '/ready-strips': typeof MainReadyStripsIndexRoute
  '/rolling-plans': typeof MainRollingPlansIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/suppliers': typeof MainSuppliersIndexRoute
  '/task-manager': typeof MainTaskManagerIndexRoute
  '/finance/cash-flow': typeof MainFinanceCashFlowIndexRoute
  '/finance/dashboard': typeof MainFinanceDashboardIndexRoute
  '/finance/expence': typeof MainFinanceExpenceIndexRoute
  '/finance/income': typeof MainFinanceIncomeIndexRoute
  '/finance/salary': typeof MainFinanceSalaryIndexRoute
  '/ready-strips/$manufactureId': typeof MainReadyStripsManufactureIdIndexRoute
  '/settings/currency': typeof MainSettingsCurrencyIndexRoute
  '/settings/finance-category': typeof MainSettingsFinanceCategoryIndexRoute
  '/settings/machine': typeof MainSettingsMachineIndexRoute
  '/settings/payment-type': typeof MainSettingsPaymentTypeIndexRoute
  '/settings/products': typeof MainSettingsProductsIndexRoute
  '/settings/raw-materials': typeof MainSettingsRawMaterialsIndexRoute
  '/settings/products/$categoryId': typeof MainSettingsProductsCategoryIdIndexRoute
  '/settings/products/$categoryId/$subcategoryId': typeof MainSettingsProductsCategoryIdSubcategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/admins': typeof MainAdminsIndexRoute
  '/clients': typeof MainClientsIndexRoute
  '/dashboard': typeof MainDashboardIndexRoute
  '/demands': typeof MainDemandsIndexRoute
  '/extra': typeof MainExtraIndexRoute
  '/finance': typeof MainFinanceIndexRoute
  '/manufactures': typeof MainManufacturesIndexRoute
  '/orders': typeof MainOrdersIndexRoute
  '/raw-material-requests': typeof MainRawMaterialRequestsIndexRoute
  '/raw-materials': typeof MainRawMaterialsIndexRoute
  '/ready-products': typeof MainReadyProductsIndexRoute
  '/ready-strips': typeof MainReadyStripsIndexRoute
  '/rolling-plans': typeof MainRollingPlansIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/suppliers': typeof MainSuppliersIndexRoute
  '/task-manager': typeof MainTaskManagerIndexRoute
  '/finance/cash-flow': typeof MainFinanceCashFlowIndexRoute
  '/finance/dashboard': typeof MainFinanceDashboardIndexRoute
  '/finance/expence': typeof MainFinanceExpenceIndexRoute
  '/finance/income': typeof MainFinanceIncomeIndexRoute
  '/finance/salary': typeof MainFinanceSalaryIndexRoute
  '/ready-strips/$manufactureId': typeof MainReadyStripsManufactureIdIndexRoute
  '/settings/currency': typeof MainSettingsCurrencyIndexRoute
  '/settings/finance-category': typeof MainSettingsFinanceCategoryIndexRoute
  '/settings/machine': typeof MainSettingsMachineIndexRoute
  '/settings/payment-type': typeof MainSettingsPaymentTypeIndexRoute
  '/settings/products': typeof MainSettingsProductsIndexRoute
  '/settings/raw-materials': typeof MainSettingsRawMaterialsIndexRoute
  '/settings/products/$categoryId': typeof MainSettingsProductsCategoryIdIndexRoute
  '/settings/products/$categoryId/$subcategoryId': typeof MainSettingsProductsCategoryIdSubcategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_main/admins/': typeof MainAdminsIndexRoute
  '/_main/clients/': typeof MainClientsIndexRoute
  '/_main/dashboard/': typeof MainDashboardIndexRoute
  '/_main/demands/': typeof MainDemandsIndexRoute
  '/_main/extra/': typeof MainExtraIndexRoute
  '/_main/finance/': typeof MainFinanceIndexRoute
  '/_main/manufactures/': typeof MainManufacturesIndexRoute
  '/_main/orders/': typeof MainOrdersIndexRoute
  '/_main/raw-material-requests/': typeof MainRawMaterialRequestsIndexRoute
  '/_main/raw-materials/': typeof MainRawMaterialsIndexRoute
  '/_main/ready-products/': typeof MainReadyProductsIndexRoute
  '/_main/ready-strips/': typeof MainReadyStripsIndexRoute
  '/_main/rolling-plans/': typeof MainRollingPlansIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/_main/suppliers/': typeof MainSuppliersIndexRoute
  '/_main/task-manager/': typeof MainTaskManagerIndexRoute
  '/_main/finance/cash-flow/': typeof MainFinanceCashFlowIndexRoute
  '/_main/finance/dashboard/': typeof MainFinanceDashboardIndexRoute
  '/_main/finance/expence/': typeof MainFinanceExpenceIndexRoute
  '/_main/finance/income/': typeof MainFinanceIncomeIndexRoute
  '/_main/finance/salary/': typeof MainFinanceSalaryIndexRoute
  '/_main/ready-strips/$manufactureId/': typeof MainReadyStripsManufactureIdIndexRoute
  '/_main/settings/currency/': typeof MainSettingsCurrencyIndexRoute
  '/_main/settings/finance-category/': typeof MainSettingsFinanceCategoryIndexRoute
  '/_main/settings/machine/': typeof MainSettingsMachineIndexRoute
  '/_main/settings/payment-type/': typeof MainSettingsPaymentTypeIndexRoute
  '/_main/settings/products/': typeof MainSettingsProductsIndexRoute
  '/_main/settings/raw-materials/': typeof MainSettingsRawMaterialsIndexRoute
  '/_main/settings/products/$categoryId/': typeof MainSettingsProductsCategoryIdIndexRoute
  '/_main/settings/products/$categoryId/$subcategoryId/': typeof MainSettingsProductsCategoryIdSubcategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/clients'
    | '/dashboard'
    | '/demands'
    | '/extra'
    | '/finance'
    | '/manufactures'
    | '/orders'
    | '/raw-material-requests'
    | '/raw-materials'
    | '/ready-products'
    | '/ready-strips'
    | '/rolling-plans'
    | '/settings'
    | '/suppliers'
    | '/task-manager'
    | '/finance/cash-flow'
    | '/finance/dashboard'
    | '/finance/expence'
    | '/finance/income'
    | '/finance/salary'
    | '/ready-strips/$manufactureId'
    | '/settings/currency'
    | '/settings/finance-category'
    | '/settings/machine'
    | '/settings/payment-type'
    | '/settings/products'
    | '/settings/raw-materials'
    | '/settings/products/$categoryId'
    | '/settings/products/$categoryId/$subcategoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admins'
    | '/clients'
    | '/dashboard'
    | '/demands'
    | '/extra'
    | '/finance'
    | '/manufactures'
    | '/orders'
    | '/raw-material-requests'
    | '/raw-materials'
    | '/ready-products'
    | '/ready-strips'
    | '/rolling-plans'
    | '/settings'
    | '/suppliers'
    | '/task-manager'
    | '/finance/cash-flow'
    | '/finance/dashboard'
    | '/finance/expence'
    | '/finance/income'
    | '/finance/salary'
    | '/ready-strips/$manufactureId'
    | '/settings/currency'
    | '/settings/finance-category'
    | '/settings/machine'
    | '/settings/payment-type'
    | '/settings/products'
    | '/settings/raw-materials'
    | '/settings/products/$categoryId'
    | '/settings/products/$categoryId/$subcategoryId'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_main/'
    | '/_auth/login/'
    | '/_main/admins/'
    | '/_main/clients/'
    | '/_main/dashboard/'
    | '/_main/demands/'
    | '/_main/extra/'
    | '/_main/finance/'
    | '/_main/manufactures/'
    | '/_main/orders/'
    | '/_main/raw-material-requests/'
    | '/_main/raw-materials/'
    | '/_main/ready-products/'
    | '/_main/ready-strips/'
    | '/_main/rolling-plans/'
    | '/_main/settings/'
    | '/_main/suppliers/'
    | '/_main/task-manager/'
    | '/_main/finance/cash-flow/'
    | '/_main/finance/dashboard/'
    | '/_main/finance/expence/'
    | '/_main/finance/income/'
    | '/_main/finance/salary/'
    | '/_main/ready-strips/$manufactureId/'
    | '/_main/settings/currency/'
    | '/_main/settings/finance-category/'
    | '/_main/settings/machine/'
    | '/_main/settings/payment-type/'
    | '/_main/settings/products/'
    | '/_main/settings/raw-materials/'
    | '/_main/settings/products/$categoryId/'
    | '/_main/settings/products/$categoryId/$subcategoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/task-manager/': {
      id: '/_main/task-manager/'
      path: '/task-manager'
      fullPath: '/task-manager'
      preLoaderRoute: typeof MainTaskManagerIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/suppliers/': {
      id: '/_main/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof MainSuppliersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/rolling-plans/': {
      id: '/_main/rolling-plans/'
      path: '/rolling-plans'
      fullPath: '/rolling-plans'
      preLoaderRoute: typeof MainRollingPlansIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ready-strips/': {
      id: '/_main/ready-strips/'
      path: '/ready-strips'
      fullPath: '/ready-strips'
      preLoaderRoute: typeof MainReadyStripsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ready-products/': {
      id: '/_main/ready-products/'
      path: '/ready-products'
      fullPath: '/ready-products'
      preLoaderRoute: typeof MainReadyProductsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/raw-materials/': {
      id: '/_main/raw-materials/'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof MainRawMaterialsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/raw-material-requests/': {
      id: '/_main/raw-material-requests/'
      path: '/raw-material-requests'
      fullPath: '/raw-material-requests'
      preLoaderRoute: typeof MainRawMaterialRequestsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/orders/': {
      id: '/_main/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof MainOrdersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/manufactures/': {
      id: '/_main/manufactures/'
      path: '/manufactures'
      fullPath: '/manufactures'
      preLoaderRoute: typeof MainManufacturesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/finance/': {
      id: '/_main/finance/'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof MainFinanceIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/extra/': {
      id: '/_main/extra/'
      path: '/extra'
      fullPath: '/extra'
      preLoaderRoute: typeof MainExtraIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/demands/': {
      id: '/_main/demands/'
      path: '/demands'
      fullPath: '/demands'
      preLoaderRoute: typeof MainDemandsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard/': {
      id: '/_main/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/clients/': {
      id: '/_main/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof MainClientsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admins/': {
      id: '/_main/admins/'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof MainAdminsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/settings/raw-materials/': {
      id: '/_main/settings/raw-materials/'
      path: '/settings/raw-materials'
      fullPath: '/settings/raw-materials'
      preLoaderRoute: typeof MainSettingsRawMaterialsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/products/': {
      id: '/_main/settings/products/'
      path: '/settings/products'
      fullPath: '/settings/products'
      preLoaderRoute: typeof MainSettingsProductsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/payment-type/': {
      id: '/_main/settings/payment-type/'
      path: '/settings/payment-type'
      fullPath: '/settings/payment-type'
      preLoaderRoute: typeof MainSettingsPaymentTypeIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/machine/': {
      id: '/_main/settings/machine/'
      path: '/settings/machine'
      fullPath: '/settings/machine'
      preLoaderRoute: typeof MainSettingsMachineIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/finance-category/': {
      id: '/_main/settings/finance-category/'
      path: '/settings/finance-category'
      fullPath: '/settings/finance-category'
      preLoaderRoute: typeof MainSettingsFinanceCategoryIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/currency/': {
      id: '/_main/settings/currency/'
      path: '/settings/currency'
      fullPath: '/settings/currency'
      preLoaderRoute: typeof MainSettingsCurrencyIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ready-strips/$manufactureId/': {
      id: '/_main/ready-strips/$manufactureId/'
      path: '/ready-strips/$manufactureId'
      fullPath: '/ready-strips/$manufactureId'
      preLoaderRoute: typeof MainReadyStripsManufactureIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/finance/salary/': {
      id: '/_main/finance/salary/'
      path: '/finance/salary'
      fullPath: '/finance/salary'
      preLoaderRoute: typeof MainFinanceSalaryIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/finance/income/': {
      id: '/_main/finance/income/'
      path: '/finance/income'
      fullPath: '/finance/income'
      preLoaderRoute: typeof MainFinanceIncomeIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/finance/expence/': {
      id: '/_main/finance/expence/'
      path: '/finance/expence'
      fullPath: '/finance/expence'
      preLoaderRoute: typeof MainFinanceExpenceIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/finance/dashboard/': {
      id: '/_main/finance/dashboard/'
      path: '/finance/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof MainFinanceDashboardIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/finance/cash-flow/': {
      id: '/_main/finance/cash-flow/'
      path: '/finance/cash-flow'
      fullPath: '/finance/cash-flow'
      preLoaderRoute: typeof MainFinanceCashFlowIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/products/$categoryId/': {
      id: '/_main/settings/products/$categoryId/'
      path: '/settings/products/$categoryId'
      fullPath: '/settings/products/$categoryId'
      preLoaderRoute: typeof MainSettingsProductsCategoryIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/products/$categoryId/$subcategoryId/': {
      id: '/_main/settings/products/$categoryId/$subcategoryId/'
      path: '/settings/products/$categoryId/$subcategoryId'
      fullPath: '/settings/products/$categoryId/$subcategoryId'
      preLoaderRoute: typeof MainSettingsProductsCategoryIdSubcategoryIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainAdminsIndexRoute: typeof MainAdminsIndexRoute
  MainClientsIndexRoute: typeof MainClientsIndexRoute
  MainDashboardIndexRoute: typeof MainDashboardIndexRoute
  MainDemandsIndexRoute: typeof MainDemandsIndexRoute
  MainExtraIndexRoute: typeof MainExtraIndexRoute
  MainFinanceIndexRoute: typeof MainFinanceIndexRoute
  MainManufacturesIndexRoute: typeof MainManufacturesIndexRoute
  MainOrdersIndexRoute: typeof MainOrdersIndexRoute
  MainRawMaterialRequestsIndexRoute: typeof MainRawMaterialRequestsIndexRoute
  MainRawMaterialsIndexRoute: typeof MainRawMaterialsIndexRoute
  MainReadyProductsIndexRoute: typeof MainReadyProductsIndexRoute
  MainReadyStripsIndexRoute: typeof MainReadyStripsIndexRoute
  MainRollingPlansIndexRoute: typeof MainRollingPlansIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
  MainSuppliersIndexRoute: typeof MainSuppliersIndexRoute
  MainTaskManagerIndexRoute: typeof MainTaskManagerIndexRoute
  MainFinanceCashFlowIndexRoute: typeof MainFinanceCashFlowIndexRoute
  MainFinanceDashboardIndexRoute: typeof MainFinanceDashboardIndexRoute
  MainFinanceExpenceIndexRoute: typeof MainFinanceExpenceIndexRoute
  MainFinanceIncomeIndexRoute: typeof MainFinanceIncomeIndexRoute
  MainFinanceSalaryIndexRoute: typeof MainFinanceSalaryIndexRoute
  MainReadyStripsManufactureIdIndexRoute: typeof MainReadyStripsManufactureIdIndexRoute
  MainSettingsCurrencyIndexRoute: typeof MainSettingsCurrencyIndexRoute
  MainSettingsFinanceCategoryIndexRoute: typeof MainSettingsFinanceCategoryIndexRoute
  MainSettingsMachineIndexRoute: typeof MainSettingsMachineIndexRoute
  MainSettingsPaymentTypeIndexRoute: typeof MainSettingsPaymentTypeIndexRoute
  MainSettingsProductsIndexRoute: typeof MainSettingsProductsIndexRoute
  MainSettingsRawMaterialsIndexRoute: typeof MainSettingsRawMaterialsIndexRoute
  MainSettingsProductsCategoryIdIndexRoute: typeof MainSettingsProductsCategoryIdIndexRoute
  MainSettingsProductsCategoryIdSubcategoryIdIndexRoute: typeof MainSettingsProductsCategoryIdSubcategoryIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainAdminsIndexRoute: MainAdminsIndexRoute,
  MainClientsIndexRoute: MainClientsIndexRoute,
  MainDashboardIndexRoute: MainDashboardIndexRoute,
  MainDemandsIndexRoute: MainDemandsIndexRoute,
  MainExtraIndexRoute: MainExtraIndexRoute,
  MainFinanceIndexRoute: MainFinanceIndexRoute,
  MainManufacturesIndexRoute: MainManufacturesIndexRoute,
  MainOrdersIndexRoute: MainOrdersIndexRoute,
  MainRawMaterialRequestsIndexRoute: MainRawMaterialRequestsIndexRoute,
  MainRawMaterialsIndexRoute: MainRawMaterialsIndexRoute,
  MainReadyProductsIndexRoute: MainReadyProductsIndexRoute,
  MainReadyStripsIndexRoute: MainReadyStripsIndexRoute,
  MainRollingPlansIndexRoute: MainRollingPlansIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
  MainSuppliersIndexRoute: MainSuppliersIndexRoute,
  MainTaskManagerIndexRoute: MainTaskManagerIndexRoute,
  MainFinanceCashFlowIndexRoute: MainFinanceCashFlowIndexRoute,
  MainFinanceDashboardIndexRoute: MainFinanceDashboardIndexRoute,
  MainFinanceExpenceIndexRoute: MainFinanceExpenceIndexRoute,
  MainFinanceIncomeIndexRoute: MainFinanceIncomeIndexRoute,
  MainFinanceSalaryIndexRoute: MainFinanceSalaryIndexRoute,
  MainReadyStripsManufactureIdIndexRoute:
    MainReadyStripsManufactureIdIndexRoute,
  MainSettingsCurrencyIndexRoute: MainSettingsCurrencyIndexRoute,
  MainSettingsFinanceCategoryIndexRoute: MainSettingsFinanceCategoryIndexRoute,
  MainSettingsMachineIndexRoute: MainSettingsMachineIndexRoute,
  MainSettingsPaymentTypeIndexRoute: MainSettingsPaymentTypeIndexRoute,
  MainSettingsProductsIndexRoute: MainSettingsProductsIndexRoute,
  MainSettingsRawMaterialsIndexRoute: MainSettingsRawMaterialsIndexRoute,
  MainSettingsProductsCategoryIdIndexRoute:
    MainSettingsProductsCategoryIdIndexRoute,
  MainSettingsProductsCategoryIdSubcategoryIdIndexRoute:
    MainSettingsProductsCategoryIdSubcategoryIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
