/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainTaskManagerIndexRouteImport } from './routes/_main/task-manager/index'
import { Route as MainSuppliersIndexRouteImport } from './routes/_main/suppliers/index'
import { Route as MainReadyProductsIndexRouteImport } from './routes/_main/ready-products/index'
import { Route as MainRawMaterialsIndexRouteImport } from './routes/_main/raw-materials/index'
import { Route as MainRawMaterialRequestsIndexRouteImport } from './routes/_main/raw-material-requests/index'
import { Route as MainManufacturesIndexRouteImport } from './routes/_main/manufactures/index'
import { Route as MainExtraIndexRouteImport } from './routes/_main/extra/index'
import { Route as MainDashboardIndexRouteImport } from './routes/_main/dashboard/index'
import { Route as MainClientsIndexRouteImport } from './routes/_main/clients/index'
import { Route as MainAdminsIndexRouteImport } from './routes/_main/admins/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as MainExtraRawMaterialsIndexRouteImport } from './routes/_main/extra/raw-materials/index'
import { Route as MainExtraProductsIndexRouteImport } from './routes/_main/extra/products/index'
import { Route as MainExtraProductsCategoryIdIndexRouteImport } from './routes/_main/extra/products/$categoryId/index'
import { Route as MainExtraProductsCategoryIdSubcategoryIdIndexRouteImport } from './routes/_main/extra/products/$categoryId/$subcategoryId/index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainTaskManagerIndexRoute = MainTaskManagerIndexRouteImport.update({
  id: '/task-manager/',
  path: '/task-manager/',
  getParentRoute: () => MainRoute,
} as any)
const MainSuppliersIndexRoute = MainSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => MainRoute,
} as any)
const MainReadyProductsIndexRoute = MainReadyProductsIndexRouteImport.update({
  id: '/ready-products/',
  path: '/ready-products/',
  getParentRoute: () => MainRoute,
} as any)
const MainRawMaterialsIndexRoute = MainRawMaterialsIndexRouteImport.update({
  id: '/raw-materials/',
  path: '/raw-materials/',
  getParentRoute: () => MainRoute,
} as any)
const MainRawMaterialRequestsIndexRoute =
  MainRawMaterialRequestsIndexRouteImport.update({
    id: '/raw-material-requests/',
    path: '/raw-material-requests/',
    getParentRoute: () => MainRoute,
  } as any)
const MainManufacturesIndexRoute = MainManufacturesIndexRouteImport.update({
  id: '/manufactures/',
  path: '/manufactures/',
  getParentRoute: () => MainRoute,
} as any)
const MainExtraIndexRoute = MainExtraIndexRouteImport.update({
  id: '/extra/',
  path: '/extra/',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardIndexRoute = MainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => MainRoute,
} as any)
const MainClientsIndexRoute = MainClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminsIndexRoute = MainAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => MainRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const MainExtraRawMaterialsIndexRoute =
  MainExtraRawMaterialsIndexRouteImport.update({
    id: '/extra/raw-materials/',
    path: '/extra/raw-materials/',
    getParentRoute: () => MainRoute,
  } as any)
const MainExtraProductsIndexRoute = MainExtraProductsIndexRouteImport.update({
  id: '/extra/products/',
  path: '/extra/products/',
  getParentRoute: () => MainRoute,
} as any)
const MainExtraProductsCategoryIdIndexRoute =
  MainExtraProductsCategoryIdIndexRouteImport.update({
    id: '/extra/products/$categoryId/',
    path: '/extra/products/$categoryId/',
    getParentRoute: () => MainRoute,
  } as any)
const MainExtraProductsCategoryIdSubcategoryIdIndexRoute =
  MainExtraProductsCategoryIdSubcategoryIdIndexRouteImport.update({
    id: '/extra/products/$categoryId/$subcategoryId/',
    path: '/extra/products/$categoryId/$subcategoryId/',
    getParentRoute: () => MainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/admins': typeof MainAdminsIndexRoute
  '/clients': typeof MainClientsIndexRoute
  '/dashboard': typeof MainDashboardIndexRoute
  '/extra': typeof MainExtraIndexRoute
  '/manufactures': typeof MainManufacturesIndexRoute
  '/raw-material-requests': typeof MainRawMaterialRequestsIndexRoute
  '/raw-materials': typeof MainRawMaterialsIndexRoute
  '/ready-products': typeof MainReadyProductsIndexRoute
  '/suppliers': typeof MainSuppliersIndexRoute
  '/task-manager': typeof MainTaskManagerIndexRoute
  '/extra/products': typeof MainExtraProductsIndexRoute
  '/extra/raw-materials': typeof MainExtraRawMaterialsIndexRoute
  '/extra/products/$categoryId': typeof MainExtraProductsCategoryIdIndexRoute
  '/extra/products/$categoryId/$subcategoryId': typeof MainExtraProductsCategoryIdSubcategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/admins': typeof MainAdminsIndexRoute
  '/clients': typeof MainClientsIndexRoute
  '/dashboard': typeof MainDashboardIndexRoute
  '/extra': typeof MainExtraIndexRoute
  '/manufactures': typeof MainManufacturesIndexRoute
  '/raw-material-requests': typeof MainRawMaterialRequestsIndexRoute
  '/raw-materials': typeof MainRawMaterialsIndexRoute
  '/ready-products': typeof MainReadyProductsIndexRoute
  '/suppliers': typeof MainSuppliersIndexRoute
  '/task-manager': typeof MainTaskManagerIndexRoute
  '/extra/products': typeof MainExtraProductsIndexRoute
  '/extra/raw-materials': typeof MainExtraRawMaterialsIndexRoute
  '/extra/products/$categoryId': typeof MainExtraProductsCategoryIdIndexRoute
  '/extra/products/$categoryId/$subcategoryId': typeof MainExtraProductsCategoryIdSubcategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_main/admins/': typeof MainAdminsIndexRoute
  '/_main/clients/': typeof MainClientsIndexRoute
  '/_main/dashboard/': typeof MainDashboardIndexRoute
  '/_main/extra/': typeof MainExtraIndexRoute
  '/_main/manufactures/': typeof MainManufacturesIndexRoute
  '/_main/raw-material-requests/': typeof MainRawMaterialRequestsIndexRoute
  '/_main/raw-materials/': typeof MainRawMaterialsIndexRoute
  '/_main/ready-products/': typeof MainReadyProductsIndexRoute
  '/_main/suppliers/': typeof MainSuppliersIndexRoute
  '/_main/task-manager/': typeof MainTaskManagerIndexRoute
  '/_main/extra/products/': typeof MainExtraProductsIndexRoute
  '/_main/extra/raw-materials/': typeof MainExtraRawMaterialsIndexRoute
  '/_main/extra/products/$categoryId/': typeof MainExtraProductsCategoryIdIndexRoute
  '/_main/extra/products/$categoryId/$subcategoryId/': typeof MainExtraProductsCategoryIdSubcategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/clients'
    | '/dashboard'
    | '/extra'
    | '/manufactures'
    | '/raw-material-requests'
    | '/raw-materials'
    | '/ready-products'
    | '/suppliers'
    | '/task-manager'
    | '/extra/products'
    | '/extra/raw-materials'
    | '/extra/products/$categoryId'
    | '/extra/products/$categoryId/$subcategoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admins'
    | '/clients'
    | '/dashboard'
    | '/extra'
    | '/manufactures'
    | '/raw-material-requests'
    | '/raw-materials'
    | '/ready-products'
    | '/suppliers'
    | '/task-manager'
    | '/extra/products'
    | '/extra/raw-materials'
    | '/extra/products/$categoryId'
    | '/extra/products/$categoryId/$subcategoryId'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_main/'
    | '/_auth/login/'
    | '/_main/admins/'
    | '/_main/clients/'
    | '/_main/dashboard/'
    | '/_main/extra/'
    | '/_main/manufactures/'
    | '/_main/raw-material-requests/'
    | '/_main/raw-materials/'
    | '/_main/ready-products/'
    | '/_main/suppliers/'
    | '/_main/task-manager/'
    | '/_main/extra/products/'
    | '/_main/extra/raw-materials/'
    | '/_main/extra/products/$categoryId/'
    | '/_main/extra/products/$categoryId/$subcategoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/task-manager/': {
      id: '/_main/task-manager/'
      path: '/task-manager'
      fullPath: '/task-manager'
      preLoaderRoute: typeof MainTaskManagerIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/suppliers/': {
      id: '/_main/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof MainSuppliersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ready-products/': {
      id: '/_main/ready-products/'
      path: '/ready-products'
      fullPath: '/ready-products'
      preLoaderRoute: typeof MainReadyProductsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/raw-materials/': {
      id: '/_main/raw-materials/'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof MainRawMaterialsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/raw-material-requests/': {
      id: '/_main/raw-material-requests/'
      path: '/raw-material-requests'
      fullPath: '/raw-material-requests'
      preLoaderRoute: typeof MainRawMaterialRequestsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/manufactures/': {
      id: '/_main/manufactures/'
      path: '/manufactures'
      fullPath: '/manufactures'
      preLoaderRoute: typeof MainManufacturesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/extra/': {
      id: '/_main/extra/'
      path: '/extra'
      fullPath: '/extra'
      preLoaderRoute: typeof MainExtraIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard/': {
      id: '/_main/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/clients/': {
      id: '/_main/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof MainClientsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admins/': {
      id: '/_main/admins/'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof MainAdminsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/extra/raw-materials/': {
      id: '/_main/extra/raw-materials/'
      path: '/extra/raw-materials'
      fullPath: '/extra/raw-materials'
      preLoaderRoute: typeof MainExtraRawMaterialsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/extra/products/': {
      id: '/_main/extra/products/'
      path: '/extra/products'
      fullPath: '/extra/products'
      preLoaderRoute: typeof MainExtraProductsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/extra/products/$categoryId/': {
      id: '/_main/extra/products/$categoryId/'
      path: '/extra/products/$categoryId'
      fullPath: '/extra/products/$categoryId'
      preLoaderRoute: typeof MainExtraProductsCategoryIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/extra/products/$categoryId/$subcategoryId/': {
      id: '/_main/extra/products/$categoryId/$subcategoryId/'
      path: '/extra/products/$categoryId/$subcategoryId'
      fullPath: '/extra/products/$categoryId/$subcategoryId'
      preLoaderRoute: typeof MainExtraProductsCategoryIdSubcategoryIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainAdminsIndexRoute: typeof MainAdminsIndexRoute
  MainClientsIndexRoute: typeof MainClientsIndexRoute
  MainDashboardIndexRoute: typeof MainDashboardIndexRoute
  MainExtraIndexRoute: typeof MainExtraIndexRoute
  MainManufacturesIndexRoute: typeof MainManufacturesIndexRoute
  MainRawMaterialRequestsIndexRoute: typeof MainRawMaterialRequestsIndexRoute
  MainRawMaterialsIndexRoute: typeof MainRawMaterialsIndexRoute
  MainReadyProductsIndexRoute: typeof MainReadyProductsIndexRoute
  MainSuppliersIndexRoute: typeof MainSuppliersIndexRoute
  MainTaskManagerIndexRoute: typeof MainTaskManagerIndexRoute
  MainExtraProductsIndexRoute: typeof MainExtraProductsIndexRoute
  MainExtraRawMaterialsIndexRoute: typeof MainExtraRawMaterialsIndexRoute
  MainExtraProductsCategoryIdIndexRoute: typeof MainExtraProductsCategoryIdIndexRoute
  MainExtraProductsCategoryIdSubcategoryIdIndexRoute: typeof MainExtraProductsCategoryIdSubcategoryIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainAdminsIndexRoute: MainAdminsIndexRoute,
  MainClientsIndexRoute: MainClientsIndexRoute,
  MainDashboardIndexRoute: MainDashboardIndexRoute,
  MainExtraIndexRoute: MainExtraIndexRoute,
  MainManufacturesIndexRoute: MainManufacturesIndexRoute,
  MainRawMaterialRequestsIndexRoute: MainRawMaterialRequestsIndexRoute,
  MainRawMaterialsIndexRoute: MainRawMaterialsIndexRoute,
  MainReadyProductsIndexRoute: MainReadyProductsIndexRoute,
  MainSuppliersIndexRoute: MainSuppliersIndexRoute,
  MainTaskManagerIndexRoute: MainTaskManagerIndexRoute,
  MainExtraProductsIndexRoute: MainExtraProductsIndexRoute,
  MainExtraRawMaterialsIndexRoute: MainExtraRawMaterialsIndexRoute,
  MainExtraProductsCategoryIdIndexRoute: MainExtraProductsCategoryIdIndexRoute,
  MainExtraProductsCategoryIdSubcategoryIdIndexRoute:
    MainExtraProductsCategoryIdSubcategoryIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
