/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainDashboardIndexRouteImport } from './routes/_main/dashboard/index'
import { Route as MainClientsIndexRouteImport } from './routes/_main/clients/index'
import { Route as MainAdminsIndexRouteImport } from './routes/_main/admins/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardIndexRoute = MainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => MainRoute,
} as any)
const MainClientsIndexRoute = MainClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminsIndexRoute = MainAdminsIndexRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => MainRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/admins/': typeof MainAdminsIndexRoute
  '/clients/': typeof MainClientsIndexRoute
  '/dashboard/': typeof MainDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/admins': typeof MainAdminsIndexRoute
  '/clients': typeof MainClientsIndexRoute
  '/dashboard': typeof MainDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_main/admins/': typeof MainAdminsIndexRoute
  '/_main/clients/': typeof MainClientsIndexRoute
  '/_main/dashboard/': typeof MainDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/' | '/admins/' | '/clients/' | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admins' | '/clients' | '/dashboard'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_main/'
    | '/_auth/login/'
    | '/_main/admins/'
    | '/_main/clients/'
    | '/_main/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard/': {
      id: '/_main/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof MainDashboardIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/clients/': {
      id: '/_main/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof MainClientsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admins/': {
      id: '/_main/admins/'
      path: '/admins'
      fullPath: '/admins/'
      preLoaderRoute: typeof MainAdminsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainAdminsIndexRoute: typeof MainAdminsIndexRoute
  MainClientsIndexRoute: typeof MainClientsIndexRoute
  MainDashboardIndexRoute: typeof MainDashboardIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainAdminsIndexRoute: MainAdminsIndexRoute,
  MainClientsIndexRoute: MainClientsIndexRoute,
  MainDashboardIndexRoute: MainDashboardIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
